INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (123, 'Rua Alegria', 'Bairro Feliz', 'Cidade das Flores', 'Ponto de Referência 1');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (456, 'Avenida da Paz', 'Bairro Tranquilo', 'Cidade Serena', 'Ponto de Referência 2');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (789, 'Rua das Rosas', 'Bairro Encantado', 'Cidade dos Sonhos', 'Ponto de Referência 3');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (101, 'Avenida da Esperança', 'Bairro Harmonia', 'Cidade da Alegria', 'Ponto de Referência 4');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (202, 'Rua da Liberdade', 'Bairro União', 'Cidade Progresso', 'Ponto de Referência 5');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (303, 'Avenida dos Sonhos', 'Bairro Felicidade', 'Cidade das Oportunidades', 'Ponto de Referência 6');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (404, 'Rua das Estrelas', 'Bairro Esperança', 'Cidade das Maravilhas', 'Ponto de Referência 7');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (505, 'Avenida da Amizade', 'Bairro Solidariedade', 'Cidade da Harmonia', 'Ponto de Referência 8');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (606, 'Rua do Progresso', 'Bairro Sucesso', 'Cidade da Prosperidade', 'Ponto de Referência 9');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (707, 'Avenida da Alegria', 'Bairro Real', 'Cidade da Felicidade', 'Ponto de Referência 10');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (808, 'Avenida da Harmonia', 'Bairro Tranquilo', 'Cidade da Paz', 'Ponto de Referência 11');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (909, 'Rua das Tulipas', 'Bairro da Aventura', 'Cidade das Maravilhas', 'Ponto de Referência 12');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (111, 'Avenida do Sol', 'Bairro da Serenidade', 'Cidade da Esperança', 'Ponto de Referência 13');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (222, 'Rua das Estrelas Cadentes', 'Bairro da Imaginação', 'Cidade da Fantasia', 'Ponto de Referência 14');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (333, 'Avenida das Borboletas', 'Bairro das Maravilhas', 'Cidade dos Sonhos', 'Ponto de Referência 15');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (444, 'Rua das Crianças Felizes', 'Bairro do Encanto', 'Cidade dos Desejos', 'Ponto de Referência 16');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (555, 'Avenida da Imaginação', 'Bairro da Alegria', 'Cidade da Magia', 'Ponto de Referência 17');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (666, 'Rua dos Anjos', 'Bairro do Sorriso', 'Cidade da Serenata', 'Ponto de Referência 18');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (777, 'Avenida dos Desejos', 'Bairro do Encantamento', 'Cidade dos Milagres', 'Ponto de Referência 19');
INSERT INTO endereco (numero_casa, rua, bairro, cidade, ponto_ref) VALUES (888, 'Rua da Magia', 'Bairro das Maravilhas', 'Cidade da Alegria Eterna', 'Ponto de Referência 20');

INSERT INTO paciente (nome, sexo, numero_cel, id_endereco, email, idade, peso) VALUES ('João Silva', 'M', '12345678901', 1, 'joao@email.com', 30, 75.5);
INSERT INTO paciente (nome, sexo, numero_cel, id_endereco, email, idade, peso) VALUES ('Maria Souza', 'F', '98765432101', 2, 'maria@email.com', 25, 60.2);
INSERT INTO paciente (nome, sexo, numero_cel, id_endereco, email, idade, peso) VALUES ('Pedro Santos', 'M', '11223344556', 3, 'pedro@email.com', 35, 82.1);
INSERT INTO paciente (nome, sexo, numero_cel, id_endereco, email, idade, peso) VALUES ('Ana Oliveira', 'F', '99887766554', 4, 'ana@email.com', 28, 57.8);
INSERT INTO paciente (nome, sexo, numero_cel, id_endereco, email, idade, peso) VALUES ('Carlos Pereira', 'M', '12398765432', 5, 'carlos@email.com', 42, 90.3);
INSERT INTO paciente (nome, sexo, numero_cel, id_endereco, email, idade, peso) VALUES ('Lúcia Rodrigues', 'F', '10293847565', 6, 'lucia@email.com', 31, 63.7);
INSERT INTO paciente (nome, sexo, numero_cel, id_endereco, email, idade, peso) VALUES ('José Almeida', 'M', '11224488900', 7, 'jose@email.com', 39, 88.9);
INSERT INTO paciente (nome, sexo, numero_cel, id_endereco, email, idade, peso) VALUES ('Sofia Gomes', 'F', '98776655443', 8, 'sofia@email.com', 29, 55.6);
INSERT INTO paciente (nome, sexo, numero_cel, id_endereco, email, idade, peso) VALUES ('Miguel Ferreira', 'M', '12347859611', 9, 'miguel@email.com', 45, 75.8);
INSERT INTO paciente (nome, sexo, numero_cel, id_endereco, email, idade, peso) VALUES ('Rita Carvalho', 'F', '99887766554', 10, 'rita@email.com', 27, 61.4);

INSERT INTO medico (nome, id_endereco, email, cfm, contrato, especializacao, horario_trabalho, numero_cel) VALUES ('Dr. João Médico', 11, 'joao_medico@email.com', 123456, 'CLT', 'Cardiologia', 'Segunda a Sexta, 8h-16h', '12345678901');
INSERT INTO medico (nome, id_endereco, email, cfm, contrato, especializacao, horario_trabalho, numero_cel) VALUES ('Dra. Maria Médica', 12, 'maria_medica@email.com', 789012, 'PJ', 'Pediatria', 'Segunda, Quarta e Sexta, 9h-17h', '98765432101');
INSERT INTO medico (nome, id_endereco, email, cfm, contrato, especializacao, horario_trabalho, numero_cel) VALUES ('Dr. Pedro Cardiologista', 13, 'pedro_cardiologista@email.com', 345678, 'CLT', 'Cardiologia', 'Terça e Quinta, 10h-18h', '11223344556');
INSERT INTO medico (nome, id_endereco, email, cfm, contrato, especializacao, horario_trabalho, numero_cel) VALUES ('Dra. Ana Pediatra', 14, 'ana_pediatra@email.com', 987654, 'PJ', 'Pediatria', 'Segunda, Quarta e Sexta, 9h-17h', '99887766554');
INSERT INTO medico (nome, id_endereco, email, cfm, contrato, especializacao, horario_trabalho, numero_cel) VALUES ('Dr. Carlos Cirurgião', 15, 'carlos_cirurgiao@email.com', 456789, 'CLT', 'Cirurgia Geral', 'Terça e Quinta, 10h-18h', '12398765432');
INSERT INTO medico (nome, id_endereco, email, cfm, contrato, especializacao, horario_trabalho, numero_cel) VALUES ('Dra. Lúcia Dermatologista', 16, 'lucia_dermatologista@email.com', 345678, 'CLT', 'Dermatologia', 'Segunda a Sexta, 8h-16h', '10293847565');
INSERT INTO medico (nome, id_endereco, email, cfm, contrato, especializacao, horario_trabalho, numero_cel) VALUES ('Dr. José Ortopedista', 17, 'jose_ortopedista@email.com', 567890, 'PJ', 'Ortopedia', 'Terça e Quinta, 9h-17h', '11224488900');
INSERT INTO medico (nome, id_endereco, email, cfm, contrato, especializacao, horario_trabalho, numero_cel) VALUES ('Dra. Sofia Ginecologista', 18, 'sofia_ginecologista@email.com', 678901, 'CLT', 'Ginecologia', 'Segunda a Sexta, 8h-16h', '98776655443');
INSERT INTO medico (nome, id_endereco, email, cfm, contrato, especializacao, horario_trabalho, numero_cel) VALUES ('Dr. Miguel Psiquiatra', 19, 'miguel_psiquiatra@email.com', 789012, 'PJ', 'Psiquiatria', 'Terça e Quinta, 10h-18h', '12347859611');
INSERT INTO medico (nome, id_endereco, email, cfm, contrato, especializacao, horario_trabalho, numero_cel) VALUES ('Dra. Rita Oftalmologista', 20, 'rita_oftalmologista@email.com', 890123, 'CLT', 'Oftalmologia', 'Segunda a Sexta, 8h-16h', '99887766554');

INSERT INTO recepcionista (nome, id_endereco, contrato) VALUES ('Recepcionista 1', 5, 'CLT');
INSERT INTO recepcionista (nome, id_endereco, contrato) VALUES ('Recepcionista 2', 6, 'CLT');
INSERT INTO recepcionista (nome, id_endereco, contrato) VALUES ('Recepcionista 3', 7, 'PJ');
INSERT INTO recepcionista (nome, id_endereco, contrato) VALUES ('Recepcionista 4', 8, 'CLT');
INSERT INTO recepcionista (nome, id_endereco, contrato) VALUES ('Recepcionista 5', 9, 'PJ');
INSERT INTO recepcionista (nome, id_endereco, contrato) VALUES ('Recepcionista 6', 10, 'CLT');
INSERT INTO recepcionista (nome, id_endereco, contrato) VALUES ('Recepcionista 7', 11, 'CLT');
INSERT INTO recepcionista (nome, id_endereco, contrato) VALUES ('Recepcionista 8', 12, 'PJ');
INSERT INTO recepcionista (nome, id_endereco, contrato) VALUES ('Recepcionista 9', 13, 'CLT');
INSERT INTO recepcionista (nome, id_endereco, contrato) VALUES ('Recepcionista 10', 14, 'PJ');

INSERT INTO receita (remedio, modo_uso, id_medico) VALUES ('Paracetamol', 'Tomar um comprimido a cada 6 horas', 1);
INSERT INTO receita (remedio, modo_uso, id_medico) VALUES ('Amoxicilina', 'Tomar um comprimido a cada 8 horas', 2);
INSERT INTO receita (remedio, modo_uso, id_medico) VALUES ('Ibuprofeno', 'Tomar um comprimido a cada 6 horas', 3);
INSERT INTO receita (remedio, modo_uso, id_medico) VALUES ('Dipirona', 'Tomar um comprimido a cada 4 horas', 4);
INSERT INTO receita (remedio, modo_uso, id_medico) VALUES ('Omeprazol', 'Tomar um comprimido antes do café da manhã', 5);
INSERT INTO receita (remedio, modo_uso, id_medico) VALUES ('Cetirizina', 'Tomar um comprimido antes de dormir', 6);
INSERT INTO receita (remedio, modo_uso, id_medico) VALUES ('Loratadina', 'Tomar um comprimido de manhã', 7);
INSERT INTO receita (remedio, modo_uso, id_medico) VALUES ('Sinvastatina', 'Tomar um comprimido à noite', 8);
INSERT INTO receita (remedio, modo_uso, id_medico) VALUES ('Metformina', 'Tomar um comprimido após as refeições', 9);
INSERT INTO receita (remedio, modo_uso, id_medico) VALUES ('Losartana', 'Tomar um comprimido de manhã', 10);

INSERT INTO consulta (obsevacao, diagnostico, id_medico, id_paciente, id_recepcionista, data_hora) VALUES ('Paciente com febre e dor de cabeça', 'Suspeita de gripe', 1, 1, 1, '2023-10-28 09:00:00');
INSERT INTO consulta (obsevacao, diagnostico, id_medico, id_paciente, id_recepcionista, data_hora) VALUES ('Exame de rotina', 'Sem problemas de saúde identificados', 2, 2, 2, '2023-10-28 10:15:00');
INSERT INTO consulta (obsevacao, diagnostico, id_medico, id_paciente, id_recepcionista, data_hora) VALUES ('Dor abdominal intensa', 'Possível apendicite', 3, 3, 3, '2023-10-28 11:30:00');
INSERT INTO consulta (obsevacao, diagnostico, id_medico, id_paciente, id_recepcionista, data_hora) VALUES ('Lesão no tornozelo', 'Entorse moderado', 4, 4, 4, '2023-10-28 13:45:00');
INSERT INTO consulta (obsevacao, diagnostico, id_medico, id_paciente, id_recepcionista, data_hora) VALUES ('Receita para refluxo', 'Prescrição de medicamento', 5, 5, 5, '2023-10-28 15:00:00');
INSERT INTO consulta (obsevacao, diagnostico, id_medico, id_paciente, id_recepcionista, data_hora) VALUES ('Exame de alergia', 'Sem alergias identificadas', 6, 6, 6, '2023-10-29 09:30:00');
INSERT INTO consulta (obsevacao, diagnostico, id_medico, id_paciente, id_recepcionista, data_hora) VALUES ('Dor de ouvido', 'Infecção no ouvido', 7, 7, 7, '2023-10-29 11:45:00');
INSERT INTO consulta (obsevacao, diagnostico, id_medico, id_paciente, id_recepcionista, data_hora) VALUES ('Acompanhamento para colesterol', 'Ajuste na dieta recomendado', 8, 8, 8, '2023-10-29 14:00:00');
INSERT INTO consulta (obsevacao, diagnostico, id_medico, id_paciente, id_recepcionista, data_hora) VALUES ('Avaliação psicológica', 'Transtorno de ansiedade identificado', 9, 9, 9, '2023-10-30 10:00:00');
INSERT INTO consulta (obsevacao, diagnostico, id_medico, id_paciente, id_recepcionista, data_hora) VALUES ('Exame de visão', 'Necessidade de óculos prescrita', 10, 10, 10, '2023-10-30 12:15:00');